# Generated by Django 5.0.2 on 2024-03-15 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_brands'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Brands',
            new_name='Brand',
        ),
    ]
