# Generated by Django 5.0.2 on 2024-03-16 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='url_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
