# Generated by Django 4.2.11 on 2024-05-25 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_productreview'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productreview',
            old_name='Image',
            new_name='image',
        ),
    ]
