# Generated by Django 5.0.2 on 2024-03-14 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='profileImage/noprofile.jpg', upload_to='profileImage/'),
        ),
    ]
